import { ScoreCard } from "@/components/ScoreCard";
import { Sparkles, Info, Target, Brain, Award, Lightbulb } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { GitHubAnalysisResponse } from "@/lib/api";

interface MLInsightsProps {
  data: GitHubAnalysisResponse;
}

const EXPERTISE_LABELS: Record<number, string> = {
  0: "Beginner",
  1: "Junior",
  2: "Mid-Level",
  3: "Senior",
  4: "Expert",
};

const DOMAIN_LABELS: Record<number, string> = {
  0: "Web Development",
  1: "Data Science",
  2: "Mobile Development",
  3: "Systems/DevOps",
  4: "Machine Learning",
  5: "Full Stack",
};

const MLInsights = ({ data }: MLInsightsProps) => {
  const expertiseLevel = data.expertise_level ?? 0;
  const domainLabel = data.domain_label ?? 0;
  const developerRank = data.developer_rank ?? 0;
  const recommendedSkills = data.recommended_skills ?? [];

  // Convert expertise level (0-4) to score (0-100)
  const expertiseScore = Math.round((expertiseLevel / 4) * 100);
  
  // Convert developer rank (0-10) to score (0-100)
  const rankScore = Math.round((developerRank / 10) * 100);

  // Calculate complexity from repos
  const avgComplexity = data.top_repos.length > 0
    ? data.top_repos.reduce((sum, repo) => sum + (repo.complexity_score || 0), 0) / data.top_repos.length
    : 0;
  const complexityScore = Math.min(Math.round(avgComplexity * 10), 100);

  // Calculate diversity from languages
  const diversityScore = Math.min(Math.round((data.most_used_languages.length / 10) * 100), 100);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <Sparkles className="h-8 w-8 text-primary" />
          ML Insights
        </h1>
        <p className="text-muted-foreground mt-1">
          Machine learning-powered analysis of @{data.username}'s GitHub profile
        </p>
      </div>

      <Alert>
        <Info className="h-4 w-4" />
        <AlertDescription>
          These predictions are generated by ML models trained on GitHub profile data,
          analyzing commit patterns, repository characteristics, and skill distributions.
        </AlertDescription>
      </Alert>

      {/* Primary ML Predictions */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card className="border-primary/50 bg-primary/5">
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Brain className="h-5 w-5 text-primary" />
              Expertise Level
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-primary">
              {EXPERTISE_LABELS[expertiseLevel] || "Unknown"}
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              Level {expertiseLevel} of 4 based on activity patterns
            </p>
          </CardContent>
        </Card>

        <Card className="border-chart-2/50 bg-chart-2/5">
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Target className="h-5 w-5 text-chart-2" />
              Domain Classification
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-chart-2">
              {DOMAIN_LABELS[domainLabel] || "General"}
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              Primary area of expertise detected
            </p>
          </CardContent>
        </Card>

        <Card className="border-chart-3/50 bg-chart-3/5">
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Award className="h-5 w-5 text-chart-3" />
              Developer Rank
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-chart-3">
              {developerRank.toFixed(2)}
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              Score out of 10 based on overall profile
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Recommended Skills */}
      {recommendedSkills.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lightbulb className="h-5 w-5 text-chart-4" />
              Recommended Skills to Learn
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-3">
              {recommendedSkills.map((item, index) => (
                <Badge
                  key={item.skill}
                  variant={index === 0 ? "default" : "secondary"}
                  className="text-sm px-4 py-2"
                >
                  {item.skill}
                  <span className="ml-2 opacity-70">Priority: {item.priority}</span>
                </Badge>
              ))}
            </div>
            <p className="text-sm text-muted-foreground mt-4">
              These skills are suggested based on your current tech stack and industry trends.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Computed Scores */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <ScoreCard
          title="Expertise Score"
          score={expertiseScore}
          description="Normalized expertise level from ML model"
        />
        <ScoreCard
          title="Developer Rank Score"
          score={rankScore}
          description="Overall profile quality score"
        />
        <ScoreCard
          title="Project Complexity"
          score={complexityScore}
          description="Average complexity of repositories"
        />
        <ScoreCard
          title="Tech Diversity"
          score={diversityScore}
          description="Breadth of languages and frameworks"
        />
      </div>

      <div className="bg-muted/50 rounded-lg p-6 border border-border">
        <h3 className="text-lg font-semibold mb-3">How These Predictions Work</h3>
        <div className="space-y-3 text-sm text-muted-foreground">
          <p>
            <strong className="text-foreground">Expertise Level:</strong> Classifier model 
            trained on developer profiles to predict experience level (0=Beginner to 4=Expert)
          </p>
          <p>
            <strong className="text-foreground">Domain Classification:</strong> Categorizes 
            your primary development area based on languages, frameworks, and project types
          </p>
          <p>
            <strong className="text-foreground">Developer Rank:</strong> Regression model 
            scoring overall profile quality from 0-10 based on activity, stars, and contributions
          </p>
          <p>
            <strong className="text-foreground">Skill Recommendations:</strong> Neural network 
            suggesting skills to learn based on your current stack and career trajectory
          </p>
        </div>
      </div>
    </div>
  );
};

export default MLInsights;